// flow-typed signature: 3fe9a1a0b4cc61fe4d5f56a10531ff57
// flow-typed version: <<STUB>>/react-native-searchbar_v^1.13.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-searchbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-searchbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-searchbar/example/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-searchbar/example/example.js' {
  declare module.exports: $Exports<'react-native-searchbar/example/example'>;
}
declare module 'react-native-searchbar/index' {
  declare module.exports: $Exports<'react-native-searchbar'>;
}
declare module 'react-native-searchbar/index.js' {
  declare module.exports: $Exports<'react-native-searchbar'>;
}
