/**
 * This file is generated code. Do not modify manually.
 * To regenerate: npm run codegen
 * See /codegen directory for implementation details.
 **/
const values = [
  '.45 Automatic',
  'Pickpocketing',
  'Prepared for the Worst',
  'Keen Eye',
  'Preposterous Sketches',
  'Higher Education',
  'Lone Wolf',
  'Streetwise',
  'Defiance',
  'Blood Pact',
  'Rise to the Occasion',
  'Scrapper',
  'Emergency Cache',
  'Roland Banks',
  'Daisy Walker',
  '"Skids" O'Toole',
  'Agnes Baker',
  'Wendy Adams',
  'Roland's .38 Special',
  'Cover Up',
  'Daisy's Tote Bag',
  'The Necronomicon',
  'On the Lam',
  'Hospital Debts',
  'Heirloom of Hyperborea',
  'Dark Memory',
  'Wendy's Amulet',
  'Abandoned and Alone',
  'Physical Training',
  'Beat Cop',
  'First Aid',
  'Machete',
  'Guard Dog',
  'Evidence!',
  'Dodge',
  'Dynamite Blast',
  'Vicious Blow',
  'Extra Ammunition',
  'Police Badge',
  'Shotgun',
  'Magnifying Glass',
  'Old Book of Lore',
  'Research Librarian',
  'Dr. Milan Christopher',
  'Hyperawareness',
  'Medical Texts',
  'Mind over Matter',
  'Working a Hunch',
  'Barricade',
  'Deduction',
  'Disc of Itzamna',
  'Encyclopedia',
  'Cryptic Research',
  'Switchblade',
  'Burglary',
  '.41 Derringer',
  'Leo De Luca',
  'Hard Knocks',
  'Elusive',
  'Backstab',
  'Sneak Attack',
  'Opportunist',
  'Cat Burglar',
  'Sure Gamble',
  'Hot Streak',
  'Forbidden Knowledge',
  'Holy Rosary',
  'Shrivelling',
  'Scrying',
  'Arcane Studies',
  'Arcane Initiate',
  'Drawn to the Flame',
  'Ward of Protection',
  'Blinding Light',
  'Fearless',
  'Mind Wipe',
  'Book of Shadows',
  'Grotesque Statue',
  'Leather Coat',
  'Scavenging',
  'Baseball Bat',
  'Rabbit's Foot',
  'Stray Cat',
  'Dig Deep',
  'Cunning Distraction',
  '"Look what I found!"',
  'Lucky!',
  'Survival Instinct',
  'Aquinnah',
  'Close Call',
  'Will to Survive',
  'Knife',
  'Flashlight',
  'Guts',
  'Perception',
  'Overpower',
  'Manual Dexterity',
  'Unexpected Courage',
  'Bulletproof Vest',
  'Elder Sign Amulet',
  'Amnesia',
  'Paranoia',
  'Haunted',
  'Psychosis',
  'Hypochondria',
  'Mob Enforcer',
  'Silver Twilight Acolyte',
  'Stubborn Detective',
  'Zoey Samaras',
  'Rex Murphy',
  'Jenny Barnes',
  'Jim Culver',
  '"Ashcan" Pete',
  'Zoey's Cross',
  'Smite the Wicked',
  'Search for the Truth',
  'Rex's Curse',
  'Jenny's Twin .45s',
  'Searching for Izzie',
  'Jim's Trumpet',
  'Final Rhapsody',
  'Duke',
  'Wracked by Nightmares',
  'Blackjack',
  'Taunt',
  'Teamwork',
  'Laboratory Assistant',
  'Strange Solution',
  'Shortcut',
  'Seeking Answers',
  'Liquid Courage',
  'Think on Your Feet',
  'Double or Nothing',
  'Hired Muscle',
  'Rite of Seeking',
  'Ritual Candles',
  'Clarity of Mind',
  'Bind Monster',
  'Fire Axe',
  'Peter Sylvestre',
  'Bait and Switch',
  'Kukri',
  'Indebted',
  'Internal Injury',
  'Chronophobia',
  'Plucky',
  'Run For Your Life',
  'Monster Slayer',
  'Lightning Gun',
  'Dr. William T. Maleson',
  'Deciphered Reality',
  'Chicago Typewriter',
  'The Gold Pocket Watch',
  'Try and Try Again',
  'The Red-Gloved Man',
  'Marie Lambeau',
  'Mystifying Song',
  'Baron Samedi',
  'Mark Harrigan',
  'Minh Thi Phan',
  'Sefina Rousseau',
  'Akachi Onyele',
  'William Yorick',
  'Lola Hayes',
  'The Home Front',
  'Shell Shock',
  'Sophie',
  'Analytical Mind',
  'The King in Yellow',
  'The Painted World',
  'Stars of Hyades',
  'Spirit-Speaker',
  'Angered Spirits',
  'Bury Them Deep',
  'Graveyard Ghouls',
  'Improvisation',
  'Crisis of Identity',
  '.32 Colt',
  'True Grit',
  '"Let me handle this!"',
  'Ever Vigilant',
  'Fieldwork',
  'Archaic Glyphs',
  'No Stone Unturned',
  'In the Know',
  'Stealth',
  'Sleight of Hand',
  'Daring Maneuver',
  'Lockpicks',
  'Alchemical Transmutation',
  'Uncage the Soul',
  'Astral Travel',
  'Spirit Athame',
  'Lantern',
  'Gravedigger's Shovel',
  'Hiding Spot',
  'Resourceful',
  'Overzealous',
  'Drawing the Sign',
  'The Thing That Follows',
  'Bandolier',
  'Stand Together',
  'Art Student',
  '"I'm outta here!"',
  'Hypnotic Gaze',
  'Newspaper',
  'Lure',
  'Relic Hunter',
  'Charisma',
  'Emergency Aid',
  'Brother Xavier',
  '"I've got a plan!"',
  'Pathfinder',
  'Contraband',
  'Adaptable',
  'Delve Too Deep',
  'Song of the Dead',
  'Oops!',
  'Fire Extinguisher',
  'Flare',
  'Smoking Pipe',
  'Painkillers',
  'Charles Ross, Esq.',
  'Forewarned',
  'Dario El-Amin',
  'A Test of Will',
  '"If it bleeds..."',
  'Springfield M1903',
  'Inquiring Mind',
  'Expose Weakness',
  'Quick Thinking',
  'Lucky Dice',
  'Alyssa Graham',
  'Dark Horse',
  'Leadership',
  '"I've had worse…"',
  'Joey "The Rat" Vigil',
  'Ace in the Hole',
  'Moonlight Ritual',
  'Jewel of Aureolus',
  'A Chance Encounter',
  'Stroke of Luck',
  'Fine Clothes',
  'Moment of Respite',
];
